-- 1. Crear tabla de Categorías
create table public.categorias (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  nombre text not null
);

-- 2. Crear tabla de Productos
drop table if exists public.productos;
create table public.productos (
  id bigint primary key, -- ID manual (importado desde CSV)
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  nombre text not null,
  descripcion text, -- Importante para detalles
  precio numeric not null,
  imagen_url text, -- Necesario para mostrar la foto
  categoria_id bigint references public.categorias(id)
);

-- 3. Habilitar Row Level Security (RLS)
alter table public.categorias enable row level security;
alter table public.productos enable row level security;

-- 4. Crear políticas de acceso público (Lectura para todos)
create policy "Categorías son públicas"
  on public.categorias for select
  using ( true );

create policy "Productos son públicos"
  on public.productos for select
  using ( true );

-- 5. Insertar datos de ejemplo (Seed Data)

-- Categorías
insert into public.categorias (nombre) values
  ('Tecnología'),
  ('Hogar'),
  ('Moda');

-- Productos (usando IDs asumiendo que empiezan en 1, 2, 3 por el orden de inserción anterior)
-- Nota: Si ejecutas esto varias veces, los IDs de categorías podrían cambiar.
-- Ajusta los 'categoria_id' según corresponda si insertas manualmente.

insert into public.productos (nombre, descripcion, precio, imagen_url, categoria_id) values
  ('Smart Watch Series X', 'Reloj inteligente con monitor de salud avanzado.', 299.00, 'https://placehold.co/600x600/f5f5f7/333333?text=Smart+Watch', 1),
  ('Wireless Buds Pro', 'Sonido de alta fidelidad con cancelación de ruido.', 149.00, 'https://placehold.co/600x600/f5f5f7/333333?text=Wireless+Buds', 1),
  ('Studio Speaker', 'Altavoz bluetooth potente para interiores.', 399.00, 'https://placehold.co/600x600/f5f5f7/333333?text=Studio+Speaker', 1),
  ('Lumière Desk Lamp', 'Lámpara LED minimalista con brillo ajustable.', 89.00, 'https://placehold.co/600x600/f5f5f7/333333?text=Desk+Lamp', 2),
  ('Minimalist Wallet', 'Billetera de cuero genuino ultra delgada.', 49.00, 'https://placehold.co/600x600/f5f5f7/333333?text=Leather+Wallet', 3),
  ('Urban Backpack', 'Mochila resistente al agua para la ciudad.', 129.00, 'https://placehold.co/600x600/f5f5f7/333333?text=Travel+Backpack', 3);
